# Generated by Django 2.1.5 on 2021-03-09 09:44

from django.db import migrations, models
import django.utils.timezone
import journal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
                ('nomer_bileta', models.IntegerField(default=journal.models.next_number, unique=True, verbose_name='Номер билета')),
                ('fio_klienta', models.CharField(max_length=50, verbose_name='ФИО клиента')),
                ('summa_zayavki', models.IntegerField(verbose_name='Сумма заявки')),
                ('status', models.CharField(choices=[('Выдан', 'Выдан'), ('Просрочен', 'Просрочен'), ('Продлен', 'Продлен'), ('Выкуп', 'Выкуп'), ('Реализован', 'Реализован')], default='Выдан', max_length=20, verbose_name='Статус')),
                ('stavka_day', models.FloatField(default=1, verbose_name='Процентная ставка в день')),
                ('srok_kredita', models.IntegerField(verbose_name='Срок займа в днях')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Дополнительные комментарии')),
                ('ostatok', models.FloatField(blank=True, null=True, verbose_name='Остаток основной суммы')),
                ('stavka_period', models.FloatField(null=True, verbose_name='Ожидаемый доход за период')),
                ('expected_stavka_day', models.FloatField(null=True, verbose_name='Ожидаемый доход в день')),
                ('fact_day', models.FloatField(blank=True, null=True, verbose_name='Начисленные проценты')),
                ('itogo_k_vyplate', models.FloatField(blank=True, null=True, verbose_name='Итого к выплате')),
                ('fact_loan_day', models.IntegerField(blank=True, verbose_name='Количество фактических дней')),
                ('date_plan_pay', models.DateTimeField(verbose_name='Дата окончания')),
                ('date_fact_pay', models.DateTimeField(blank=True, null=True, verbose_name='Дата фактического окончания')),
                ('zalog', models.TextField(verbose_name='Наименование залога')),
                ('credit_user', models.ForeignKey(on_delete=models.SET('Удаленный пользователь'), to='users.Officer', verbose_name='Кредитный специалист')),
            ],
        ),
        migrations.CreateModel(
            name='Zalog_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип залога')),
            ],
        ),
    ]
