# Generated by Django 2.1.5 on 2021-02-24 11:27

from django.db import migrations, models
import django.utils.timezone
import journal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_zayavki', models.IntegerField(default=journal.models.next_number, unique=True, verbose_name='Номер заявки')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
                ('fio_klienta', models.CharField(max_length=100, verbose_name='ФИО клиента/Наименование компании')),
                ('summa_zayavki', models.IntegerField(verbose_name='Сумма заявки')),
                ('purpose', models.CharField(choices=[('Потребительские', 'Потребительские'), ('Бизнес', 'Бизнес')], max_length=200, verbose_name='Цель кредита')),
                ('srok_kredita', models.IntegerField(verbose_name='Срок кредита')),
                ('zalog', models.CharField(choices=[('Заработная плата', 'Заработная плата'), ('Доход от бизнеса', 'Доход от бизнеса'), ('Поручительство', 'Поручительство'), ('Недвижимость', 'Недвижимость'), ('Движимое имущество', 'Движимое имущество')], max_length=20, verbose_name='Обеспечение')),
                ('status', models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Одобрено', 'Одобрено'), ('Отказано', 'Отказано')], max_length=20, verbose_name='Статус')),
                ('istochnik', models.CharField(choices=[('Заработная плата', 'Заработная плата'), ('Доход от бизнеса', 'Доход от бизнеса'), ('Другие доходы', 'Другие доходы')], max_length=20, verbose_name='Источник погашения')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина отказа/Условия одобрения')),
                ('date_refuse', models.DateTimeField(blank=True, default=journal.models.one_day_more, null=True, verbose_name='Дата отказа/одобрения')),
                ('protokol_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер протокола')),
                ('credit_user', models.ForeignKey(on_delete=models.SET('Удаленный пользователь'), to='users.Officer', verbose_name='Кредитный специалист')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Продукт кредитования')),
                ('interest_rate', models.FloatField(default=28, verbose_name='Процентная ставка')),
                ('interest_rate_2', models.FloatField(blank=True, null=True, verbose_name='Процентная ставка вторая')),
                ('interest_rate_3', models.FloatField(blank=True, null=True, verbose_name='Процентная ставка третья')),
                ('sum', models.IntegerField(default=100000, verbose_name='Сумма 1')),
                ('sum_2', models.IntegerField(blank=True, null=True, verbose_name='Сумма 2')),
                ('sum_3', models.IntegerField(blank=True, null=True, verbose_name='Сумма 3')),
                ('commission', models.FloatField(default=0, verbose_name='Комиссия за выдачу')),
                ('commission_2', models.FloatField(blank=True, null=True, verbose_name='Комиссия за выдачу 2')),
                ('commission_3', models.FloatField(blank=True, null=True, verbose_name='Комиссия за выдачу 3')),
                ('commission_cash', models.FloatField(default=0, verbose_name='Коммиссия за обналичивание')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='product',
            field=models.ForeignKey(on_delete=models.SET('Удаленный продукт'), to='journal.Product', verbose_name='Наименование продукта'),
        ),
    ]
