# Generated by Django 2.1.5 on 2021-03-02 05:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import journal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, verbose_name='ФИО клиента')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('phone_number_reserve', models.CharField(max_length=10, verbose_name='Доп. номер телефона')),
                ('comment', models.TextField(null=True, verbose_name='Комментарий по клиенту')),
            ],
        ),
        migrations.CreateModel(
            name='Zalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание залога')),
            ],
        ),
        migrations.CreateModel(
            name='Zalog_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип залога')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
                ('nomer_bileta', models.IntegerField(default=journal.models.next_number, unique=True, verbose_name='Номер заявки')),
                ('summa_zayavki', models.IntegerField(verbose_name='Сумма заявки')),
                ('status', models.CharField(choices=[('Выдан', 'Выдан'), ('Просрочен', 'Просрочен'), ('Продлен', 'Продлен'), ('Выкуп', 'Выкуп'), ('Реализован', 'Реализован')], max_length=20, verbose_name='Статус')),
                ('stavka_day', models.FloatField(default=1, verbose_name='Процентная ставка в день')),
                ('srok_kredita', models.IntegerField(verbose_name='Срок займа в днях')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Дополнительные комментарии')),
                ('zalog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='journal.Zalog', verbose_name='Наименование залога')),
                ('credit_user', models.ForeignKey(on_delete=models.SET('Удаленный пользователь'), to='users.Officer', verbose_name='Кредитный специалист')),
                ('fio_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Client', verbose_name='ФИО клиента')),
            ],
        ),
    ]
