# Generated by Django 2.1.5 on 2021-03-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrihodRashod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField(verbose_name='Сумма транзакции')),
                ('type', models.CharField(choices=[('Приход', 'Приход'), ('Расход', 'Расход')], max_length=20, verbose_name='Тип транзакции')),
                ('date', models.DateField(verbose_name='Дата транзакции')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Product', verbose_name='Займ')),
            ],
        ),
    ]
