# Generated by Django 2.1.5 on 2021-03-01 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание залога')),
                ('price', models.FloatField(verbose_name='Оценка Залога')),
                ('sell_price', models.FloatField(verbose_name='Цена Реализации')),
            ],
        ),
        migrations.CreateModel(
            name='Zalog_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип залога')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='credit_user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_refuse',
        ),
        migrations.RemoveField(
            model_name='client',
            name='fio_klienta',
        ),
        migrations.RemoveField(
            model_name='client',
            name='istochnik',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nomer_zayavki',
        ),
        migrations.RemoveField(
            model_name='client',
            name='product',
        ),
        migrations.RemoveField(
            model_name='client',
            name='protokol_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='client',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='client',
            name='srok_kredita',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='summa_zayavki',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zalog',
        ),
        migrations.AddField(
            model_name='client',
            name='client_name',
            field=models.CharField(default='Клиент', max_length=50, verbose_name='ФИО клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий по клиенту'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='979', max_length=10, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number_reserve',
            field=models.CharField(default='90', max_length=10, verbose_name='Доп. номер телефона'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('nomer_bileta', models.IntegerField(default=journal.models.next_number, unique=True, verbose_name='Номер заявки')),
                ('summa_zayavki', models.IntegerField(verbose_name='Сумма заявки')),
                ('ostatok', models.FloatField(null=True, verbose_name='Остаток основной суммы')),
                ('status', models.CharField(choices=[('Выдан', 'Выдан'), ('Просрочен', 'Просрочен'), ('Продлен', 'Продлен'), ('Выкуп', 'Выкуп'), ('Реализован', 'Реализован')], max_length=20, verbose_name='Статус')),
                ('stavka_day', models.FloatField(null=True, verbose_name='Процентная ставка в день')),
                ('stavka_period', models.FloatField(null=True, verbose_name='Ожидаемый доход за период')),
                ('expected_stavka_day', models.FloatField(null=True, verbose_name='Ожидаемый доход в день')),
                ('fact_day', models.FloatField(null=True, verbose_name='Начисленные проценты')),
                ('itogo_k_vyplate', models.FloatField(null=True, verbose_name='Итого к выплате')),
                ('srok_kredita', models.IntegerField(verbose_name='Срок займа в днях')),
                ('fact_loan_day', models.IntegerField(verbose_name='Количество фактических дней')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
                ('date_plan_pay', models.DateTimeField(verbose_name='Дата окончания')),
                ('date_fact_pay', models.DateTimeField(null=True, verbose_name='Дата фактического окончания')),
                ('zalog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='journal.Zalog', verbose_name='Наименование продукта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Дополнительные комментарии')),
                ('credit_user', models.ForeignKey(on_delete=models.SET('Удаленный пользователь'), to='users.Officer', verbose_name='Кредитный специалист')),
                ('fio_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Client', verbose_name='ФИО клиента')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='zalog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='zalog',
            name='zalog_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Zalog_types', verbose_name='Тип залога'),
        ),
    ]
