# Generated by Django 2.1.5 on 2021-03-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_prihodrashod'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Дата')),
                ('is_calculated', models.BooleanField(verbose_name='Начисление')),
                ('calc_sum', models.FloatField(verbose_name='Сумма начислений')),
            ],
        ),
    ]
