# Generated by Django 2.1.5 on 2021-03-10 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_workdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_fact_pay',
            field=models.DateField(blank=True, null=True, verbose_name='Дата фактического окончания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_plan_pay',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заявки'),
        ),
    ]
