# Generated by Django 2.1.5 on 2021-03-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20210310_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='telephone_number',
            field=models.CharField(default='0', max_length=10, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
